version: '3.7'
services:
  postgres:
    image: postgres:16.0
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=movies
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5438:5432'